name: Example Action

on:
  push:
    branches:
      - main  # Trigger this action when code is pushed to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 21f3001383@ds.study.iitm.ac.in
        run: echo "Hello, world!"

